openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /upload:
    post:
      summary: Upload file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
